### ISSUE TITLE
Sortierung v. Werken

### ISSUE THREAD

**Issue by wachauer** [Middle-High-German-Conceptual-Database/MHDBDB#54]
Bei Werkanzeige, Beleg-Ergebnissen usw. ist nicht klar, wie das sortiert wird, vmtl. irgendeine ID.
Gewünschte Sortiermöglichkeit: alphabetisch/Autor/Genre

![image](https://user-images.githubusercontent.com/65647672/234272411-07d76982-7a2d-49d6-b072-d5457faadada.png)

**Comment by juliahin** [comment]
Notiz: Die alphabetische Reihung der Texte ist nicht exakt.

![image](https://github.com/Middle-High-German-Conceptual-Database/MHDBDB/assets/122389061/a84e697b-b5a4-4a8e-acd0-ee364b4c5749)
